import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginLeft: 16,
    marginRight: 16,
    marginTop: 62,
    paddingBottom: 32,
  },
  backButton: {
    marginLeft: 4,
    marginBottom: 26.22,
  },
  titleContainer: {
    marginBottom: 32,
    width: 358,
  },
  title: {
    color: "#2E2F31",
    fontSize: 32,
    fontFamily: "Manrope-Bold",
    fontWeight: "700",
    letterSpacing: 0,
  },
  imageContainer: {
    padding: 0,
    width: "100%",
    letterSpacing: 0,
    marginBottom: 35,
  },
  step: {
    color: "#713100",
    fontWeight: 500,
    marginBottom: 8,
    fontSize: 14,
  },
  subTitle: {
    fontSize: 20,
    color: "#2E2F31",
    marginBottom: 24,
    lineHeight: 28,
    letterSpacing: 0,
    fontWeight: 500,
  },
  category: { fontSize: 16, fontWeight: "bold", marginTop: 15 },
  itemContainer: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    marginVertical: 6,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 14,
  },
  selectedItemContainer: {
    backgroundColor: "#fbeee6",
    borderColor: "#713100",
  },
  iconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#eee",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  selectedIconWrapper: {
    backgroundColor: "#713100",
  },
  itemText: { fontSize: 16 },
  nextButton: {
    marginTop: 20,
    backgroundColor: "#713100",
    padding: 14,
    alignItems: "center",
    borderRadius: 20,
  },
  nextText: { color: "#fff", fontSize: 16, fontWeight: "bold" },
  label: {
    fontSize: 16,
    fontWeight: 500,
    lineHeight: 20,
    marginBottom: 8,
    letterSpacing: 0,
  },
  input: {
    borderWidth: 1,
    gap: 16,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 12,
    paddingRight: 12,
    borderColor: "#C5C5D1",
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
  },
  addPhotosText: {
    fontWeight: 600,
    fontSize: 14,
    color: "#713100",
  },
  Button: {
    marginTop: 20,
    backgroundColor: "#713100",
    paddingVertical: 16,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  submitText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 16,
  },
  buttonContainer: {
    paddingLeft: 16,
    paddingRight: 16,
    flexDirection: "column",
    height: 94,
    paddingTop: 16,
    marginBottom: 24,
  },
});
  